Improved responsiveness of panning and rotation
thorstenhater/arbor-gui pull request #50
Opened 2021-05-18 14:37 UTC by Helveg

Rotation now scales with mouse speed, and panning with zoom level.

Ideally these hardcoded sensitivities could become settings somewhere, for now I tuned them on my machine so that rotation felt good, but this might depend a lot on mouse sensitivity and preference. For the panning I had a better metric, I tuned it so that on all zoom levels the CV markers would stick to the mouse as close as possible during panning.

2021-05-20 06:27 UTC, thorstenhater requested changes
Thanks, however, in general I am wary of tweaking things to a specific setup. Could you add settings for mouse sensitivity in the menus?

2021-05-20 06:27 UTC, thorstenhater commented on src/window.cpp
> +        delta_pos.x = - dx * pow(gui_state_zoom, 1.2) / 12;
How did you arrive at this formula?

2021-05-20 06:27 UTC, thorstenhater commented on src/window.cpp
> +extern float gui_state_zoom;
I would prefer having less global variables rather than more.

2021-05-20 06:55 UTC, Helveg commented
Sure, I'll see if I can find directions in Dear ImGui's docs or bother you on Slack ;p

2021-08-28 09:26 UTC, thorstenhater commented
Hi @Helveg,

I am gearing up towards formally releasing this and moving the project over to the arbor-sim org.
This means that by the end of next week this repo will be archived and I will likely close all resolved
PRs by then.

T

2021-08-29 13:23 UTC, Helveg commented
That's fine, I don't have the bandwidth to implement the requested changes, feel free to close :)

2021-08-30 06:38 UTC, thorstenhater commented
Ok, thanks for the reply. I also overhauled the navigation in a branch that will be merged into the release.

2021-08-30 06:38 UTC, closed without merging